## USB port
port: /dev/ttyACM1


##### Calibration ####
### accelerometer
accel_x_min: -258.0
accel_x_max: 258.0
accel_y_min: -257.0
accel_y_max: 253.0
accel_z_min: -269.0
accel_z_max: 238.0

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [18.8804, -63.4868, -72.1681]
magn_ellipsoid_transform: [[0.900673, 0.0356804, -0.00611356], [0.0356804, 0.899987, 0.0444685], [-0.00611356, 0.0444685, 0.979130]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -5.41
gyro_average_offset_y: -15.09
gyro_average_offset_z:  14.12
